[[employee]]
requester = "Иванов Иван"
vpn_user = "ivanov_i"
workstation_host = "10.32.5.121"
enabled = true

[[employee]]
requester = "Петров Петр"
vpn_user = "petrov_p"
workstation_host = "ws-petrov"
enabled = false
